# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A1lQ1l6lla0X_7-uf3C4imSEnKqce9Tp
"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

years = [[2025], [2026], [2018], [2017], [2016]]
values = [220, 240, 260, 280, 300]

years_train, years_test, values_train, values_test = train_test_split(years, values, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(years_train, values_train)

future_years = [[2025]]
predicted_values = model.predict(future_years)
print(predicted_values)

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

years = [[2015], [2016], [2017], [2018], [2019], [2020]]
values = [200, 220, 240, 260, 280, 300]

years_train, years_test, values_train, values_test = train_test_split(years, values, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(years_train, values_train)

future_year=[[2025]]
predicted_value = model.predict(future_year)
print(f"Predicted value for 2025: {predicted_value[0]}")

