# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bHvz2qd3Z63t7bs5TzMblmkmVPXrHbOp
"""

def sum_of_even_numbers(n):
    if n < 1:
        return "Please enter a positive integer greater than 0."

    # Sum of even numbers using a loop
    total = 0
    for i in range(2, n + 1, 2):  # Start from 2 and increment by 2
        total += i

    return total

# Get input from the user
try:
    n = int(input("Enter a positive integer: "))
    result = sum_of_even_numbers(n)
    print(f"The sum of all even numbers between 1 and {n} is: {result}")
except ValueError:
    print("Please enter a valid integer.")

words = ['Hello', 'World']
result = " ".join(words)
print(result)

#lstrip() and rstrip() - Removes whitespace from the left or right side of the string, respectively.
text = "   Hello World   "
print(text.lstrip())
print(text.rstrip())

def check_even_odd(number):
    if number % 2 == 0:
        return "Even"
    else:
        return "Odd"
result = check_even_odd(4)
print(result)

