# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XYd5fMCPY8zC9aRc9czqh_rLOHMBhcmx
"""

def greet (name):
    print("NAMASTE" +name)
name="Shreya Parida"
greet(name)

