# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQ4xqbdCghGFWg4RJ9BxJD-5OjJivqYo
"""

cxj[poiuytrewq  `1234567890-\ qwedrftghyjkl;'
              ASDFGHJKL.;/'']

my_array = [1, 2, 3, 4, 5]
my_array[2] = 10  # Change the element at index 2 to 10
print(my_array)  # Output: [1, 2, 10, 4, 5]

my_array = [1, 2, 3]
my_array.append(4)  # Add 4 to the end of the array
print(my_array)  # Output: [1, 2, 3, 4]

my_array = [1, 2, 3]
my_array.insert(1, 10)  # Insert 10 at index 1
print(my_array)  # Output: [1, 10, 2, 3]

my_array = [1, 2, 3, 4, 5]
del my_array[2]  # Delete the element at index 2
print(my_array)  # Output: [1, 2, 4, 5]

